### ISSUE TITLE
`json.RawMessage` scan issue

### ISSUE THREAD

**Issue by shawn246** [uptrace/bun#172] opened 2021-09-08 17:51 UTC
```
type Foo struct {
	ID    string
	Value json.RawMessage
}

func main() {
	dsn := "YOUR_OWN_CONNECTION_STRING"
	sqldb, err := sql.Open("mysql", dsn)
	if err != nil {
		panic(err)
	}
	db := bun.NewDB(sqldb, mysqldialect.New())

	ctx := context.Background()
	if _, err = db.NewCreateTable().Model((*Foo)(nil)).Exec(ctx); err != nil {
		panic(err)
	}

	objs := []Foo{
		{ID: "1", Value: []byte("1")},
		{ID: "2", Value: []byte("2")},
	}
	if _, err = db.NewInsert().Model(&objs).Exec(ctx); err != nil {
		panic(err)
	}

	var objs1 []*Foo
	var objs2 []*Foo
	if err = db.NewSelect().Model(&objs1).Order("id").Scan(ctx); err != nil {
		panic(err)
	}
	fmt.Println(objs1[0].Value)
	if err = db.NewSelect().Model(&objs2).Order("id desc").Scan(ctx); err != nil {
		panic(err)
	}
	fmt.Println(objs1[0].Value)
}
```
Print objs1[0].Value twice, get different results. The second select changes the result of the first select. 

[https://github.com/uptrace/bun/blob/6d83830b2f76db166739729f5c4444e21ccdff64/schema/scan.go#L348](https://github.com/uptrace/bun/blob/6d83830b2f76db166739729f5c4444e21ccdff64/schema/scan.go#L348)
I think the problem is bun does the shallow copy for []byte type while scanning. 
The problem is temporarily resolved by adding a scan hook for the struct:
```
func (o *Foo) AfterScan(ctx context.Context) error {
	if o.Value != nil {
		v := make([]byte, len(o.Value))
		copy(v, o.Value)
		o.Value = v
	}
	return nil
}
```

**Comment by vmihailenco** [comment] 2021-09-09 07:24
You are right even though I was not able to reproduce this behavior in tests... Should be fixed by https://github.com/uptrace/bun/pull/173

**Closed** 2021-09-09 07:26 UTC

**Comment by shawn246** [comment] 2021-09-09 08:04
Your test case can not reproduce the problem. The two select get the exactly same result in your test case.

In my test case, two select are executed with different order which make sure the result are different.

**Comment by vmihailenco** [comment] 2021-09-09 08:55
Thanks - updated the test :+1:
