### ISSUE TITLE
Array of timestamps is not properly escaped upon insert to Postgres

### ISSUE THREAD

**Issue by MickeyShnaiderman-RecoLabs** [uptrace/bun#800] opened 2023-03-13 11:53 UTC
When Bun is presented with a timestamp value, it escapes it with single quotes (`'`) regardless of whether the value is inside an array. That creates values like `'{'2023-03-12 19:16:26.461461+00:00','2023-03-12 19:16:26.461461+00:00'}'`, while the desired escaping is with `"`: `'{"2023-03-12 19:16:26.461461+00:00","2023-03-12 19:16:26.461461+00:00"}'`.

Assume `db` is a valid connection object to Postgres (`*bun.DB`) and the table exists:

```go
type TableModel struct {
	bun.BaseModel `bun:"my_table"`
	AllActionTimes []time.Time `bun:"all_action_times,array,notnull"`
}

modelToInsert := &TableModel {
	AllActionTimes: []time.Time{time.Now(), time.Now()},
}

fmt.Println(db.NewInsert().Model(&modelToInsert).String())
```

Would print 
```SQL
INSERT INTO "my_table" ("all_action_times") VALUES ('{'2023-03-13 11:15:52.195023+00:00','2023-03-13 11:15:52.195024+00:00'}')
```
which is not a valid query because of the timestamp escaping.

**Comment by smyrman** [comment] 2023-04-12 19:50
Duplicate of #702?

**Comment by vmihailenco** [comment] 2023-04-13 05:49
Closing as a duplicate of https://github.com/uptrace/bun/issues/702

**Closed by vmihailenco** 2023-04-13 05:49 UTC
