### ISSUE TITLE
scanonly not working

### ISSUE THREAD

**Issue by imraan-go** [uptrace/bun#489] opened 2022-03-19 16:20 UTC
Looks like fields declared with scanonly is not included in Scan. The field gets ommitted from select queries. But according to the documentation, It should only omit this field from insert and update.

```go


type Customer struct {
	Id                string       `json:"id" bun:"id,pk,scanonly"`
	PhoneNumber       string       `json:"phone_number" bun:"phone_number"`
}
customer := Customer{}
err := repo.db.NewSelect().
		Model(&customer).
		Where("phone_number = ?", "524-322-3322").
		Limit(1).
		Scan(ctx)

```

The above code produces the following  query:

```sql

 SELECT "customer"."phone_number" FROM "customers" AS "customer" WHERE (phone_number = '01700000000') LIMIT 1

```

**Comment by vmihailenco** [comment] 2022-03-20 08:12
This is a duplicate of https://github.com/uptrace/bun/issues/374#issuecomment-998558989

**Closed by vmihailenco** 2022-03-20 08:12 UTC
