### ISSUE TITLE
Support for replica(read/write)

### ISSUE THREAD

**Issue by nilpntr** [uptrace/bun#1068] opened 2024-11-20 10:16 UTC
I'm trying to setup bun to split the read and write queries over 2 url's(1 for read/write and one for read only). The problem is `bun.NewDB` is expecting an sql.DB struct but maybe it should expect an interface implementing all the sql.DB functionality which makes room for these type of setups. Are you guys planning on having such things in the future?

**Comment by vmihailenco** [comment] 2024-11-20 11:52
Duplicate of https://github.com/uptrace/bun/issues/1037

**Closed by vmihailenco** 2024-11-20 11:52 UTC
