### ISSUE TITLE
struct tags "autoincrement"

### ISSUE THREAD

**Issue by panlw** [uptrace/bun#479] opened 2022-03-06 13:10 UTC
## PostgreSQL

[Don't use serial](https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_serial)

> For new applications, **identity columns** should be used instead.

**Comment by vmihailenco** [comment] 2022-03-08 11:35
We probably should add a separate tag `,identity` and use for PostgreSQL and MSSQL.

**Comment by oGi4i** [comment] 2022-06-29 23:14
I would like to implement this, but I have some concerns.

Brief reminder on the current implementation:
1. Both MSSQL and PG dialects support the `autoincrement` tag.
2. PG does this simply by mapping the data type to `SMALLSERIAL`, `SERIAL`, `BIGSERIAL` respectively.
3. MSSQL does this by implementing the Identity feature, which adds the `IDENTITY` keyword on column creation.

So I see 3 solutions:
1. Comply with the current implementation. This means adding the Identity feature to the PG dialect. The problem is that this would case a breaking change, because I don't see a way to both support the data type mapping and the usage of the `IDENTITY` keyword. So I guess we would have to choose to only support the later.
2. Add an independent `identity` tag. This means that for the PG dialect the `autoincrement` tag works the same, we implement the use of the `IDENTITY` keywork only with the `identity` tag present. Also I guess both tags would need to be mutually exclusive. For the MSSQL the `identity` tag would have to work the same as the `autoincrement` tag or it would be ignored completely, which would be a bit confusing imho.
3. Add the `identity` tag as an additional tag for the `autoincement` tag. This means for the PG dialect with only the `autoincrement` tag present it would work the same. If there are both tags (`autoincrement` and `identity`) present, then we use the `IDENTITY` keyword. For the MSSQL both cases would work the same or the `identity` tag would be ignored completely, which would also be a bit confusing imho.

Another concern is that PG and MSSQL have different syntax for the `IDENTITY` keyword.
1. PG requires the following statement `column_name type GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY`
2. While MSSQL only requires just a single `IDENTITY` keyword

As I see it, this could be implemented by implementing an additional interface (something like an `IdentityAppender`) by the dialects.

@vmihailenco would love to here your thoughts on this.

**Comment by vmihailenco** [comment] 2022-07-01 09:40
@oGi4i I think we need a separate feature-flag for PostgreSQL called `feature.GeneratedBy` or something. You can check for that flag [here](https://github.com/uptrace/bun/blob/master/query_table_create.go#L169) and append `GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY` as required.

Models can use the same `,autoincrement,identity` tag to enable this behavior on PostgreSQL / MSSQL.

**Comment by oGi4i** [comment] 2022-07-01 18:31
> @oGi4i I think we need a separate feature-flag for PostgreSQL called `feature.GeneratedBy` or something. You can check for that flag [here](https://github.com/uptrace/bun/blob/master/query_table_create.go#L169) and append `GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY` as required.

OK, so we add a new feature-flag for PostgreSQL.
But the place that you suggest we should append the `IDENTITY` statement will be in conflict with the data type mapping done [here](https://github.com/uptrace/bun/blob/master/dialect/pgdialect/dialect.go#L76-L85). We will get a statement like `BIGSERIAL GENERATED BY DEFAULT AS IDENTITY` which is invalid because you can't mix `SERIAL` and `IDENTITY`.

> Models can use the same ,autoincrement,identity tag to enable this behavior on PostgreSQL / MSSQL.

Currently `,autoincrement` is enough to use `IDENTITY` for MSSQL. But you would need `,autoincrement,identity` to use it for PostgreSQL?

**Comment by vmihailenco** [comment] 2022-07-02 07:27
>statement will be in conflict with the data type mapping done [here](https://github.com/uptrace/bun/blob/master/dialect/pgdialect/dialect.go#L76-L85)

We will need to disable that behavior as well when `identity` is enabled.

>Currently ,autoincrement is enough to use IDENTITY for MSSQL. But you would need ,autoincrement,identity to use it for PostgreSQL?

I am open for suggestions, but let's not break current behavior. Perhaps just `,identity` should be enough for PostgreSQL?

**Closed** 2022-07-05 08:56 UTC
Labels: enhancement, good first issue

**Comment by necipallef** [comment] 2022-10-10 21:32
> I am open for suggestions, but let's not break current behavior. Perhaps just ,identity should be enough for PostgreSQL?
In PostgreSQL, when using `NewInsert()`, if only `,identity` is used and it is missing from the model, it tries to save the field as `0`. If `,autoincrement,identity` is used, then it tries to save the field as `DEFAULT`, which works. So, `,identity` alone is not working.
```	github.com/uptrace/bun v1.1.8 // indirect
	github.com/uptrace/bun/dialect/pgdialect v1.1.8 // indirect
	github.com/uptrace/bun/driver/pgdriver v1.1.8 // indirect
	github.com/uptrace/bun/extra/bundebug v1.1.8 // indirect
	```
