### ISSUE TITLE
Getting randomly EOF error

### ISSUE THREAD

**Issue by xhkocatepe** [uptrace/bun#525] opened 2022-04-26 06:08 UTC
We receive sometimes an EOF error from bun as ` *errors.errorString: EOF` .
It is important that we have get issue `sometimes` ; same query, same db, same data, sometimes return data, but sometimes get `EOF` error. 
We get a workaround solution for using retry policy. We try to run same query until we successfully get data from db.

**Is there any real solution for this issue?**

PS:If it is necessary, I can share part of query.

**Comment by xhkocatepe** [comment] 2022-05-16 07:47
Hello Everyone :) Is there any response?

**Comment by hhuseyinpay** [comment] 2022-05-19 09:42
Which driver do you use? If you use the pgdriver, there is a hint in [the documentation ](https://bun.uptrace.dev/postgres/#debugging)

**Comment by xhkocatepe** [comment] 2022-06-19 13:25
yeah we are using pgdriver 1.0.19. It is not working shared file from you.

**Comment by vmihailenco** [comment] 2022-06-22 07:44
Closing, because there is no way to reproduce the problem. Please re-open if you have more details.

**Closed by vmihailenco** 2022-06-22 07:44 UTC

**Comment by xhkocatepe** [comment] 2022-06-22 08:59
We can reproduce the problem many times. What kind of details dou you want?

**Comment by htdvisser** [comment] 2022-07-30 14:54
I've been able to reproduce this issue: https://gist.github.com/htdvisser/fe1145e832fe2f323ee609e866fb59be

I'm investigating further and will try to contribute a fix.

**Comment by hypnoglow** [comment] 2023-02-21 09:59
We still getting a lot of random EOFs with the 1.1.9 bun version. I have no reproducer though at this point.
